### ISSUE TITLE
Instructor Feedback - Week 4 Hibernate/DAO Exercise

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [nikofenev/ScheduleGenerator#1]
Looks good, just one question:

- [x] Is this passing? https://github.com/nikofenev/ScheduleGenerator/blob/ef0d9ed5c552aef0df61b53654e659a24dbc4040/src/tests/java/edu/matc/persistence/UserHibernateDaoTest.java#L60. Seems like it's comparing the ArrayList to a returned user?

**Comment by nikofenev** [comment]
Yes, I actually overrode the equals method in my User class.
```
    @Override
    public boolean equals(Object obj) {

        User thisUser = (User) obj;

        return thisUser.userid == userid //if userId are same
                && thisUser.firstName.equalsIgnoreCase(firstName) //if firstNames are same
                && thisUser.lastName.equalsIgnoreCase(lastName) // if lastNames are same
                && thisUser.userName.equalsIgnoreCase(userName); // if userNames are same
    }
```

**Comment by pawaitemadisoncollege** [comment]
Great, thanks for following up.
