### ISSUE TITLE
Code Review by Aaron Briggs

### ISSUE THREAD

**Issue by abriggs3** [nikofenev/ScheduleGenerator#5]
# Design/Code Review 2

#### Reviewer: Aaron Briggs

|Item |Criteria|Rating | Comments/Suggestions|
|--------|---------|---------------|---|
||| Use the following scale:<br> 1= It needs more work<br>  2 = Somewhat<br> 3 = Yes it is great|Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|  |  |
|**Application Functionality**|1. At least 25% of the application's target functionality has been built and is working. </br>2. In comments/suggestions field list and evaluate the functionality that has been implemented.  | 3| The project is coming along well. Looks like at least 25% of it is working. Currently, an employee can be added and some of the scheduling tasks completed and stored. The multi-date and time selector is a great feature. Suggestion, there are couple of broken features, get those fixed. ;)
|**Unit Tests**|1. Code coverage stats meets or exceeds the developer's code coverage goal. <br> 2. Unit tests are meaningful - they test the business logic and data access aspects of the application (simple methods like getters and setters are not tested) </br> 3. In comments/suggestions field list the code coverage goal and actual current coverage percentage. <br>4. @Before/@BeforeClass/@After/@AfterClass used to reduce redundant code, like creation of entities.<br>5. A test database is used for unit testing and data is cleaned up/reset before or after the tests, so that the tests are re-runnable without developer intervention/cleanup. | 3| The unit testing of the major components work and run repeatedly without failure. The annotations are used correctly and add to the efficiency of the the code. The tests to the DB work and the DB is returned to original condition before the running of the test suit. Suggestion, some additional tests could be added for code outside the DOAs.
|**JSPs**|1. Templating is used to eliminate redundant code(for example, header.jsp, footer.jsp, etc.) <br> 2. CSS or a CSS framework has been implemented to give the site a professional look and feel<br> 3. There is not any embedded java code in the JSPs (EL and JSTL is used appropriately).| 3| The site looks awesome! Phenomenal background and menu choices. The site uses both a structure and CSS template system. Did I mention how great it looks? Yes, well it does. 
|**Code quality**|1. Methods are single-purpose<br> 2. Classes appropriately-sized classes (no monster classes). </br > 3. Methods do not contain many branches or loops that could be simplified or broken up into smaller methods. <br /> 4. The same lines of code are not repeated at all <br> 5. Uses interfaces/super/subclass relationships rather than repeating functionality in multiple classes? For example, using a generic/abstract dao. <br />6. Code does not contain any hard-coded values that should be in a properties file </br> 7. Appropriate logging levels are used. Info, debug, error, etc. </br> 8. There are not any System.out.println() or printStackTrace() statements in the code </br> 9. Package, class, method and variable names are descriptive and meaningful. <br/>10. Include in the comments section what technique you used to evaluate the items above. Using a code quality plug-in is highly recommended as a starting point for code quality reviews. | 3| Code is looking good. Use of the 'generic doa' is an efficient choice. Logging is used and package names and structure make sense. Code looks good. |
|**Web Service/API integration**|1. Web service/api has been identified in the project problem statement/list of technologies. </br> 2. Web Service integration has been built. <br /> 3. Web Service integration has been unit tested. | 1| This is still a work in progress. I am thinking that a service that will return the days of federal and state holidays would be useful.|
|**Independent research topic**| 1. Topic has been identified in the project problem statement/list of technologies. </br> 2. Topic research is complete and documented. <br /> 3. Topic has been implemented in the project| 2| This is still in progress. Priority has been given to getting the site working, and this has been on the back burner. I am sure it will see more attention soon.|  
|**Key takeaways**|List at least 3 things you learned while reviewing this project that will help you in your own project.| 3|1. The sites CSS template is great; I would take for myself but that might be a bit tacky. 2. Generic DOAs save code, I should use one on my site, oh I did ;) 3. Bootstrap has some nice features for calendars and drop down menus

**Comment by nikofenev** [comment]
Thanks for the detailed feedback Aaron. I will be working on those issues you mentioned on Thursday and Friday this week. And also thank you for the API suggestion, that will be great addition to the website.
