### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by miarnold** [nikofenev/ScheduleGenerator#7]
# Design/Code Review 3
  
  ## Project: scheduleGenerator
  
  ### Developer: NIKO-LIE
  
  #### Reviewer: Mack Daddy
  
  |Category|Criteria|Rating/Comments|
  |--------|---------|---------------|
  |**Project Overview**|| |
  ||Which planned functionality has been met? | most of it is met, have some tweaking to do with generating the schedule |
  || What planned functionality has not been met? | you dont currently have the website making a schedule in the end, but you know that and are currently working on it |
  ||Describe the GitHub history and what it demonstrates about the project progress during the semester.| commits are normal and everything looks good. its up to date in github. |
  ||Describe how peer and instructor feedback/recommendations were incorporated into the project.| he listened well and made mistakes we all gave him as things came up |
  ||Other comments/notes?| looks great, getting close to the end |
  |**JSPs**|| |
  ||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| used bootstrap and the site looks great. all the servlets flow nicely and really show the amount of time you spent on them, which was a lot |
  ||Other comments/notes?| none |
  |**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation | the code quality is acutally really good because of the code quality plugin you are using, and i thought that was really smart of you.|Other comments/notes?|  |
  |**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy|there is logging in the right place, but you said that once you fixed something you took out the logs, so there's not as much as i expected|Other comments/notes?| 
  |**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After|everything is tested, and you made it weasy by using the generic dao so testing wasnt nearly as bad as doing it with seprerate daos. great work||
  ||Other comments/notes?| |
  |**Security**|Evaluate authentication/authorization:| the security works and the log out works as well and you can log in and out with no problem|
  ||Is it implemented correctly and working locally as well as on AWS?| yes and tomcat auth works on aws currently
  ||Other comments/notes?| |
  |**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?| this API you used is nice and its a past holiday api and i dont see too much handling if it went down or out of service.  |
  ||Other comments/notes?| |
  |**Independent research topic**| What is the independent research topic?| |
  ||Is the independent research topic/technique implemented in the project?| code quality plug in. this is implemented and everything is working and looks good! |
  ||Other comments/notes?| |
  |**Deployment**| Has the application been successfully deployed to AWS or another hosting service?| yes the service is hosted on aws and up and running|
  ||Is the hosted application fully functioning?| it has full functionality that the local site does |
  ||Other comments/notes?| great work! |

**Comment by nikofenev** [comment]
Thank you for the detailed feedback.
